#!/usr/bin/env node
// Regenerate the generated blocks in README.md.
//
// Rewrites the regions between the SIZE and SHOT markers with text derived
// from the measured binary sizes and the showcase example name. Invoked by
// .github/workflows/readme-assets.yml after every release build; also handy
// locally, e.g.:
//
//     node scripts/update_readme.mjs --example simples \
//         --windows-bytes 226304 --mac-bytes 1361234

import { readFileSync, writeFileSync } from "node:fs";

const SIZE_BEGIN = "<!-- SIZE:BEGIN";
const SIZE_END = "<!-- SIZE:END -->";
const SHOT_BEGIN = "<!-- SHOT:BEGIN";
const SHOT_END = "<!-- SHOT:END -->";

function human(bytes) {
  if (bytes >= 1_000_000) return `${(bytes / 1_000_000).toFixed(1)}Mb`;
  if (bytes >= 1_000) return `${Math.round(bytes / 1_000)}kb`;
  return `${bytes}b`;
}

function sizeBlock(example, windows, mac) {
  return [
    `${SIZE_BEGIN} (generated by scripts/update_readme.mjs - do not edit by hand) -->`,
    `* Small binaries - the \`${example}\` example compiles to ${human(windows)} ` +
      `for Windows, and ${human(mac)} for Mac, in release.`,
    SIZE_END,
  ].join("\n");
}

function shotBlock(example) {
  return [
    `${SHOT_BEGIN} (generated by scripts/update_readme.mjs - do not edit by hand) -->`,
    `The \`${example}\` example running natively on each platform:`,
    "",
    "| Windows | macOS |",
    "| ------- | ----- |",
    `| ![${example} example on Windows](docs/screenshots/${example}-windows.png)` +
      ` | ![${example} example on macOS](docs/screenshots/${example}-macos.png) |`,
    SHOT_END,
  ].join("\n");
}

function replace(readme, begin, end, block, label) {
  const start = readme.indexOf(begin);
  const finish = readme.indexOf(end, start);
  if (start === -1 || finish === -1) {
    console.error(`error: ${label} markers (${begin} ... ${end}) not found in README`);
    process.exit(1);
  }
  return readme.slice(0, start) + block + readme.slice(finish + end.length);
}

function parseArgs(argv) {
  const args = { readme: "README.md" };
  for (let i = 0; i < argv.length; i += 2) {
    const [flag, value] = [argv[i], argv[i + 1]];
    if (value === undefined) {
      console.error(`error: missing value for ${flag}`);
      process.exit(1);
    }
    const key = { "--example": "example", "--windows-bytes": "windows", "--mac-bytes": "mac", "--readme": "readme" }[flag];
    if (!key) {
      console.error(`error: unknown argument ${flag}`);
      process.exit(1);
    }
    if (key === "example" || key === "readme") {
      args[key] = value;
    } else {
      args[key] = Number(value);
      if (!Number.isFinite(args[key])) {
        console.error(`error: ${flag} must be a number, got "${value}"`);
        process.exit(1);
      }
    }
  }
  if (!args.example) {
    console.error("usage: update_readme.mjs --example <name> --windows-bytes <n> --mac-bytes <n> [--readme <path>]");
    process.exit(1);
  }
  return args;
}

const args = parseArgs(process.argv.slice(2));
let readme = readFileSync(args.readme, "utf8");
readme = replace(readme, SIZE_BEGIN, SIZE_END, sizeBlock(args.example, args.windows, args.mac), "size");
readme = replace(readme, SHOT_BEGIN, SHOT_END, shotBlock(args.example), "screenshot");
writeFileSync(args.readme, readme);
console.log(`updated ${args.readme}`);
